name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you're using a different branch for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Update this if you have a different build command
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.3.9
        with:
          branch: gh-pages  # The branch you want to deploy to (often 'gh-pages')
          folder: build  # The folder where your built files are located
